/* Ergänzungen aus den Unterrichtsmaterialien vom 08.10.2026. */
(() => {
  'use strict';
  const esc = s => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
  const code = s => `<div class="code-block"><div class="code-toolbar"><span>Arduino · C++</span><button type="button" class="copy-code">Code kopieren</button></div><pre><code>${esc(s)}</code></pre></div>`;
  const fig = (file,alt,caption='Abbildung aus dem bereitgestellten Arbeitsblatt.') => `<figure class="figure"><img src="assets/${file}" alt="${alt}" loading="lazy"><figcaption>${caption}</figcaption></figure>`;
  const table = (head,rows) => `<div class="table-wrap"><table><thead><tr>${head.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  const note = (title,text) => `<div class="callout"><strong>${title}</strong><p>${text}</p></div>`;
  const step = (id,title,body,prompts=[],extra={}) => ({id,title,body,fields:prompts.map((label,i)=>({key:String(i),label})),...extra});
  const quiz = (question,options,answer,explanation) => ({question,options,answer,explanation});
  const chapter = id => COURSE.find(m=>m.id===id);

  // Die vorhandenen Kapitel- und Schritt-IDs bleiben für gespeicherten Fortschritt erhalten.
  chapter('start').steps[0].body=chapter('start').steps[0].body.replace('Deine schriftlichen Antworten speichert dieser Browser; sichere sie regelmäßig über „Mein Lernheft“.','Schreibe deine schriftlichen Antworten mit Datum und der angegebenen Überschrift von Hand in dein Heft. Der Browser speichert nur deinen Fortschritt und die Eingaben der Selbstchecks.');
  COURSE.forEach(m=>m.steps.forEach(s=>s.fields.forEach(f=>{f.label=f.label.replace('Beschreibe hier,','Beschreibe im Heft,').replace('Deine vervollständigte Zusammenfassung:','Schreibe die vollständig ergänzte Zusammenfassung in dein Heft.');})));

  window.QUIZ_BANKS = {
    'quiz-arduino': [
      quiz('Was bewirkt pinMode(9, OUTPUT);?', ['Pin 9 wird als Ausgang vorbereitet.','Pin 9 wird als Eingang vorbereitet.','Pin 9 wird sofort auf HIGH gesetzt.','Das Programm wartet 9 Sekunden.'],0,'pinMode legt die Richtung fest. Welcher Signalpegel ausgegeben wird, bestimmst du danach mit digitalWrite oder analogWrite.'),
      quiz('Pin 9 ist am Uno R3 als OUTPUT eingestellt. Was bewirkt digitalWrite(9, LOW);?', ['Der Pin gibt ungefähr 9 V aus.','Der Pin wird zum Eingang.','Der Ausgang wird auf ungefähr 0 V gesetzt.','Der Arduino wird ausgeschaltet.'],2,'LOW ist der niedrige Signalpegel. In unserer LED-Schaltung geht die LED damit aus. Die Wirkung bei anderen Bauteilen hängt von der Schaltung ab.'),
      quiz('Wozu dient digitalRead(Pin)?', ['Es verändert die Drehrichtung.','Es liest HIGH oder LOW an einem digitalen Eingang.','Es misst immer die genaue Spannung.','Es legt einen Pin als Ausgang fest.'],1,'digitalRead liefert einen digitalen Zustand. Es liefert keinen beliebigen Spannungsmesswert und schaltet den Eingang nicht als Ausgang.'),
      quiz('Wie lange wartet delay(10);?', ['10 Millisekunden.','10 Sekunden.','10 Minuten.','Eine Zehntelsekunde.'],0,'1000 ms sind 1 s. Deshalb sind 10 ms gleich 0,01 s. In dieser Zeit werden die folgenden normalen Programmanweisungen noch nicht ausgeführt.'),
      quiz('Was passiert mit dem Inhalt von loop()?', ['Er läuft nur einmal nach jedem Start.','Er wird nach setup immer wieder ausgeführt.','Er läuft nur beim Drücken des Tasters.','Er wird vom Arduino ignoriert.'],1,'setup läuft einmal zur Vorbereitung. Danach beginnt loop nach jedem Durchlauf erneut.'),
      quiz('Welcher Datentyp kann Zahlen mit Nachkommastellen speichern?', ['int','long','float','pinMode'],2,'float kann zum Beispiel 3.14 speichern. int und long sind Datentypen für ganze Zahlen; pinMode ist ein Befehl.'),
      quiz('Was bewirkt Serial.println("Hallo"); nach Serial.begin(9600);?', ['Es schreibt nur eine leere Zeile.','Es ändert Pin 9.','Es gibt Hallo mit anschließendem Zeilenumbruch aus.','Es wartet 9600 Millisekunden.'],2,'println gibt hier den übergebenen Text und danach einen Zeilenumbruch aus. Serial.println() ohne Argument erzeugt dagegen nur einen Zeilenumbruch.'),
      quiz('Welche Schleife ist besonders übersichtlich, wenn ein Block genau dreimal laufen soll?', ['delay','for','pinMode','Serial.print'],1,'Eine for-Schleife bündelt Startwert, Bedingung und Zähländerung. Auch andere Lösungen sind möglich, aber for passt besonders gut zu einer bekannten Anzahl.'),
      quiz('Was bewirkt analogWrite(9, 255); am Uno R3, wenn die normale PWM-Funktion verfügbar ist?', ['Eine Wechselspannung mit 255 V.','Pin 9 bleibt HIGH: 100 % Einschaltzeit.','Pin 9 wird als Eingang benutzt.','Der Pin ist die ganze Zeit LOW.'],1,'255 ist der größte übliche analogWrite-Wert. Bei 100 % Einschaltzeit bleibt der Ausgang HIGH; er wechselt dann nicht mehr zwischen HIGH und LOW. Die Servo-Bibliothek kann am Uno R3 die PWM-Funktion an 9 und 10 beeinflussen.'),
      quiz('Welche Werte kann random(10, 20) liefern?', ['10 bis einschließlich 20.','Nur 10 oder 20.','Ganze Zahlen von 10 bis 19.','Beliebige Dezimalzahlen zwischen 10 und 20.'],2,'Die erste Grenze ist eingeschlossen, die zweite ausgeschlossen. Darum sind 10, 11, …, 19 möglich.'),
      quiz('Wann führt if (Bedingung) { ... } seinen Block aus?', ['Immer.','Wenn die Bedingung wahr ist.','Nur wenn die Bedingung falsch ist.','Nur beim ersten Durchlauf von loop.'],1,'if prüft eine Bedingung. Bei einem Vergleich nutzt du zum Beispiel ==. Ein einzelnes = weist dagegen einen Wert zu.')
    ],
    'quiz-statik': [
      quiz('Welche Verformung gehört zur Druckbelastung?', ['Dehnung','Stauchung','Nur Drehung','Keine Verformung'],1,'Druckkräfte wirken aufeinander zu und können den Körper zusammendrücken. Diese Verkürzung heißt Stauchung.'),
      quiz('Welche Verformung gehört zur Zugbelastung?', ['Stauchung','Dehnung','Nur Scherung','Nur Knicken'],1,'Zugkräfte ziehen den Körper auseinander. Die Verlängerung heißt Dehnung.'),
      quiz('Welche Belastung tragen die gespannten Ketten einer Schaukel hauptsächlich?', ['Druck','Schub','Zug','Nur Biegung'],2,'Die Last des Sitzes und der Person zieht an den Ketten. Die Ketten leiten diese Zugkraft an den oberen Balken weiter.'),
      quiz('Welche Last kann ein biegsames Seil nicht als tragendes Bauteil aufnehmen?', ['Zug durch einen hängenden Behälter','Zug entlang des Seils','Eine axiale Druckkraft','Zug als gespannte Diagonale'],2,'Ein Seil gibt unter Druck nach. Es kann eine Konstruktion nur in der Richtung aussteifen, in der es gespannt wird.'),
      quiz('Welche axialen Belastungen kann ein geeigneter Stab grundsätzlich aufnehmen?', ['Nur Zug','Nur Druck','Zug und Druck','Keine Kräfte'],2,'Ein Stab kann gezogen oder gedrückt werden. Ob er die konkrete Last aushält, hängt von Material, Querschnitt, Länge und Befestigung ab.'),
      quiz('Welche Größe zeigt in der Messreihe mit gleichartigen Fäden gleicher Dicke keine klare systematische Wirkung auf die Reißkraft?', ['Die untersuchte Fadenlänge','Das Fadenmaterial','Die gesamte Querschnittsfläche','Die Zahl paralleler Fäden'],0,'Die Mittelwerte der Längenreihe liegen ungefähr gleich hoch. Das ist eine Aussage zu diesen Daten und zu vergleichbaren Fäden; reale Fehlstellen können Ergebnisse beeinflussen.'),
      quiz('Wie verändert eine größere Querschnittsfläche die Reißkraft gleichartiger Fäden bei gleichmäßiger Belastung?', ['Sie nimmt grundsätzlich ab.','Sie wird immer null.','Sie kann zunehmen, weil mehr Material die Last trägt.','Sie hängt nur von der Farbe ab.'],2,'Die Reißkraft ist eine Kraft in Newton. Die Zugfestigkeit des Materials ist dagegen eine auf die Fläche bezogene Materialeigenschaft. Mehr Fläche bedeutet nicht automatisch ein anderes Material.'),
      quiz('Wie würde ein zugfesteres Fadenmaterial bei gleichem Querschnitt die gemessenen Reißkräfte typischerweise verändern?', ['Die Werte werden null.','Die Werte müssen kleiner werden.','Die Werte können höher liegen.','Nur die Achsenbeschriftung ändert sich.'],2,'Ein zugfesteres Material kann bei gleichem Querschnitt eine größere Zugkraft aufnehmen. Im Diagramm liegen die Messpunkte dann typischerweise höher.'),
      quiz('Was kann die Druckbelastbarkeit kurzer, kompakter Stützen aus gleichem Material erhöhen?', ['Ein kleinerer Querschnitt','Ein größerer Querschnitt','Nur eine andere Farbe','Das Entfernen des Materials'],1,'Mehr Querschnitt verteilt die Drucklast auf mehr Material. Bei langen, schlanken Stäben muss zusätzlich die Knickstabilität betrachtet werden.'),
      quiz('Was kann mit einem langen, dünnen Stab unter Druck passieren?', ['Er wird automatisch ein Seil.','Er knickt seitlich aus.','Er nimmt nur Zug auf.','Er kann sich niemals verformen.'],1,'Knicken ist ein seitliches Ausweichen. Eine geeignete Halterung in der Mitte verkürzt die freie Knicklänge und kann den Stab stabilisieren.'),
      quiz('Welche Änderung hat im vereinfachten Knickvergleich keinen wesentlichen mechanischen Einfluss?', ['Die freie Länge','Der Durchmesser','Die seitliche Halterung','Die Farbe eines dünnen Anstrichs'],3,'Länge, Querschnitt, Material und Befestigung beeinflussen die Knickstabilität. Die Farbe allein verändert diese Größen nicht wesentlich.'),
      quiz('Wie kann eine ausreichend steife Stabdiagonale einen gelenkigen Rechteckrahmen stabilisieren?', ['Sie macht alle Verbindungen beweglicher.','Sie teilt den Rahmen in Dreiecke.','Sie entfernt eine Ecke.','Sie ersetzt den Rahmen durch ein loses Seil.'],1,'Eine Diagonale verhindert das freie Verschieben der Ecken zum schiefen Viereck. Die Stabdiagonale und ihre Verbindungen müssen die Kräfte übertragen.'),
      quiz('Was bedeutet Scheibe bei der Aussteifung eines Rahmens?', ['Eine lose Glasscheibe in jedem Fall','Ein gut befestigtes, flächiges Bauteil, zum Beispiel eine Rückwand','Ein einzelnes Zahnrad','Ein ungespanntes Seil'],1,'Eine Scheibe kann Schubkräfte als Fläche übertragen. Entscheidend ist ihre geeignete Verbindung mit dem Rahmen.'),
      quiz('Was verringert im rechteckigen Balkenmodell die Durchbiegung besonders stark, wenn Material, Breite, Spannweite und Last gleich bleiben?', ['Weniger Höhe in Biegerichtung','Mehr Höhe in Biegerichtung','Nur eine andere Farbe','Eine größere Spannweite'],1,'Die Höhe steht in der dritten Potenz im Nenner: Doppelte Höhe ergibt im Modell ein Achtel der Durchbiegung.'),
      quiz('Ein Balken liegt auf zwei Endauflagern und wird in der Mitte nach unten belastet. Wo entsteht beim gezeigten Durchbiegen Druck?', ['An der unteren Randzone','An der oberen Randzone','Nur außerhalb des Balkens','Nirgends'],1,'Beim nach unten durchgebogenen Balken wird die obere Randzone zusammengedrückt und die untere gedehnt. Bei anderer Auflagerung oder Biegerichtung können die Seiten wechseln.')
    ]
  };
  chapter('arduino').source='Arduino-Folien, Befehls-Arbeitsblatt und Kahoot-Tabelle Arduino-Befehle';
  chapter('arduino').steps.push(step('quiz','Arduino-Selbstcheck: 11 Fragen',`<p>Du hast die Befehle wiederholt. Prüfe nun dein Verständnis mit den Fragen aus der bereitgestellten Quiztabelle. Du bekommst nach jeder Antwort eine Erklärung und kannst erneut überlegen.</p><p>Es gibt kein Zeitlimit. Lies bei einer Unsicherheit im passenden Schritt nach.</p>`,['Notiere zwei Befehle, die du noch verwechselst. Erkläre im Heft ihre unterschiedliche Wirkung.'],{widget:'quiz-arduino'}));
  chapter('lampe').steps.push(step('kommentieren','Dein Lampenprogramm verständlich kommentieren',`<p>Die Wiederholungsfolien fordern dich auf, den fertigen Code Zeile für Zeile zu erklären. Ein guter Kommentar beschreibt den Zweck. Er hilft dir später, einen Fehler zu finden.</p>${code('const int ledPin = 5; // Der Name steht für unseren LED-Anschluss.\nint stufe = 0;       // Merkt sich: aus, mittel oder hell.\n\n// Nur ein neu erkannter Tastendruck erhöht die Stufe.\n// Nach Stufe 2 folgt wieder Stufe 0.')}<p>Erkläre besonders die Tastererkennung, das Entprellen und den Unterschied zwischen <code>stufe</code> und dem PWM-Wert. Das Zurücksetzen erfolgt <strong>nach</strong> der höchsten Stufe. Sonst würdest du die volle Helligkeit überspringen.</p>`,['Schreibe ein kurzes Stück deines Lampencodes mit eigenen Kommentaren ins Heft. Erkläre dann den Ablauf bei drei aufeinanderfolgenden Tastendrücken.','Beschreibe, warum ein dauerhaft gedrückter Taster nur einmal weiterschalten soll.'],{solution:'<p>Die Stufenfolge ist 0 → 1 → 2 → 0. Die Variable stufe beschreibt einen Zustand. Die PWM-Werte 0, 128 und 255 steuern die LED. Ein neuer stabiler Wechsel auf LOW zählt als Tastendruck.</p>'}));
  chapter('servo').source='Arbeitsblatt Servomotor 2025 und Folien Servomotor';
  chapter('servo').steps.push(step('alltag','Wo ist eine gezielte Position hilfreich?',`<p>Ein gewöhnlicher Positionsservo soll einen Winkel anfahren. Deshalb passt er beispielsweise zu einer Modellauto-Lenkung, einem Robotergreifer oder einer kleinen Kamerahalterung. Bei den Beispielen geht es um eine <strong>gezielte Stellung</strong>.</p><p>Ein Ventilator soll dagegen fortlaufend rotieren. Dafür passt ein DC-Motor oder ein anderer geeigneter Dauerläufer. Ein normaler SG90-Positionsservo ist dafür ungeeignet. Es gibt besondere Servos für kontinuierliche Rotation; sie funktionieren anders als unser Positionsservo.</p>${table(['Aufgabe','Passende Bewegungsanforderung'],[['Ring zwischen Lösung und Luftstrom bewegen','Winkel beziehungsweise Position gezielt ändern.'],['Luftschraube antreiben','Kontinuierlich mit geeigneter Drehzahl drehen.'],['Zeiger für die Lampenstufe','Drei wiederholbare Winkel anzeigen.']])}`,['Nenne zwei Alltags- oder Modellanwendungen eines Positionsservos und erkläre, warum eine genaue Stellung wichtig ist.','Entscheide für Dispenser und Luftschraube deiner Maschine, welche Bewegungsart nötig ist. Begründe.'],{solution:'<p>Bei der Lenkung muss der Winkel der Räder stimmen; beim Greifer die Stellung der Finger. Ein Positionsservo kann den Ring zwischen zwei Stellungen bewegen. Die Luftschraube braucht dauernde Rotation. Eure konkrete Mechanik entscheidet über die Auswahl.</p>'}));

  const motor=chapter('antrieb');
  motor.title='DC-Motor und Transistor';motor.subtitle='Steuersignal und Motorleistung';motor.time='mehrere kurze Versuche';motor.source='Arbeitsblatt Motoren ansteuern – Leistungstransistor und Folien DC-Motor/Getriebe';
  motor.steps.push(
    step('vergleich','Servo und DC-Motor vergleichen',`<p>Ein Motor wandelt elektrische Energie in mechanische Bewegung um. Ein <strong>Positionsservo</strong> enthält zusätzlich Getriebe, Positionsmessung und eine Regelung. Du gibst einen Zielwinkel vor. Bei einem einfachen <strong>DC-Motor</strong> legst du über eine geeignete Leistungsstufe Spannung an. Der Motor dreht weiter; ein Winkel wird nicht automatisch eingehalten.</p>${fig('dc-motor.png','Kleiner Gleichstrommotor mit zwei Anschlüssen')}${table(['Merkmal','Positionsservo','Einfacher DC-Motor'],[['Steuerziel','Bestimmten Winkel anfahren','Kontinuierliche Drehung'],['Anschlüsse beim Schulmodell','Versorgung, GND, Steuersignal','Zwei Motoranschlüsse an einer Leistungsstufe'],['Geschwindigkeit oder Position','Zielstellung wird intern geregelt','Drehzahl hängt unter anderem von Ansteuerung und Last ab'],['Projektbeispiel','Ring oder Zeiger positionieren','Luftschraube antreiben']])}<p>Kleine Spielzeuge oder Modellantriebe können DC-Motoren enthalten. In Haushaltsgeräten kommen verschiedene Motortypen vor; nicht jeder Ventilator besitzt denselben Motor wie unser Schulmodell.</p>`,['Übernimm eine Vergleichstabelle mit drei selbst erklärten Unterschieden zwischen Positionsservo und DC-Motor.','Nenne zwei mögliche Anwendungen eines DC-Motors und erläutere seine Aufgabe.']),
    step('richtung','Zwei Motoranschlüsse und die Drehrichtung',`<p>Bei einem einfachen Bürsten-DC-Motor bestimmt die Polung die Drehrichtung. Vertauschst du die Spannung an seinen Anschlüssen, kann sich die Richtung umkehren. Praktisch geschieht das mit einer <strong>dafür geeigneten H-Brücke oder einem Motortreiber</strong>.</p>${note('Die Tabelle ist ein Denkmodell','Die beiden Einträge stehen für Motoranschlüsse hinter einer Leistungsstufe. Verbinde den Motor niemals direkt mit zwei Arduino-Signalpins. Unsere einfache Transistorstufe kann nur in einer Richtung ein- und ausschalten.')}${table(['Motoranschluss A','Motoranschluss B','Spannungsunterschied'],[['LOW','LOW','Beide gleich: kein elektrischer Antrieb'],['LOW','HIGH','Spannung mit einer Polung'],['HIGH','LOW','Spannung mit der umgekehrten Polung'],['HIGH','HIGH','Beide gleich: kein elektrischer Antrieb']])}<p>Bei gleicher Spannung an beiden Anschlüssen hängt Bremsen oder freies Auslaufen vom verwendeten Treiber und dessen Betriebsart ab. Übernimm dafür die Angaben eurer konkreten Schaltung.</p>`,['Zeichne die Tabelle ins Heft. Ergänze die zwei entgegengesetzten Drehrichtungen als „Richtung 1“ und „Richtung 2“.','Erkläre, warum eine einzelne Transistorstufe die Drehrichtung nicht umkehrt.'],{hints:['Entscheidend ist die Spannung zwischen den Motoranschlüssen, nicht ihre einzelnen Namen.'],solution:'<p>LOW/HIGH und HIGH/LOW haben entgegengesetzte Polungen. Eine einzelne Transistorstufe unterbricht nur denselben Strompfad. Sie vertauscht die Motoranschlüsse nicht.</p>'}),
    step('leistung','Warum ein Signalpin keinen 10-W-Motor versorgt',`<p>Leistung beschreibt, wie viel Energie pro Zeit umgesetzt wird. Für elektrische Leistung nutzt du:</p><div class="formula">P = U · I</div><p><strong>U</strong> ist die Spannung in Volt, <strong>I</strong> der Strom in Ampere und <strong>P</strong> die Leistung in Watt. Für den Uno R3 nennt Arduino <strong>20 mA pro I/O-Pin</strong>. Das sind 0,020 A. Im vereinfachten Rechenvergleich ergibt 5 V · 0,020 A eine Leistung von 0,10 W.</p>${note('Korrigierte Angabe im Material','Die Angabe „200 mA pro Pin“ aus dem ursprünglichen Motor-Arbeitsblatt ist falsch. Wir rechnen hier mit 20 mA. Der Wert 0,10 W ist eine vereinfachte Vergleichsrechnung und keine Freigabe, einen Motor am Signalpin zu betreiben.')}<p>Ein Motor mit 10 W braucht deutlich mehr Leistung. Dazu kommen beim Anlaufen oft höhere Ströme. Deshalb übernimmt eine passend dimensionierte Leistungsstufe das Schalten einer geeigneten Motorversorgung. Ein 9-V-Block ist nicht automatisch eine geeignete Versorgung für jeden Motor.</p>`,['Rechne 20 mA in Ampere um und berechne 5 V · 0,020 A. Schreibe Ansatz, Ergebnis und Einheit ins Heft.','Um welchen Faktor sind 10 W größer als 0,10 W? Erkläre die Folgerung für die Motoransteuerung.'],{hints:['Milli bedeutet ein Tausendstel. Für den Faktor teilst du 10 durch 0,10.'],solution:'<p>20 mA = 0,020 A. P = 5 V · 0,020 A = 0,10 W. 10 W / 0,10 W = 100. Der Beispielmotor braucht also hundertmal so viel Leistung wie dieser vereinfachte Pinvergleich ergibt. Die Energie kommt aus der Motorversorgung.</p>'}),
    step('anschluesse','Basis, Kollektor und Emitter erkennen',`<p>Im Arbeitsblatt siehst du den Leistungstransistor <strong>TIP120</strong>. Er hat die Anschlüsse <strong>B</strong> für Basis, <strong>C</strong> für Kollektor und <strong>E</strong> für Emitter. Der TIP120 ist ein Darlington-Transistor. Für unseren Schaltplan genügt zunächst: Ein kleiner Basisstrom steuert einen größeren Strom im Motorzweig.</p>${fig('tip120.png','TIP120 mit im Arbeitsblatt markierten Anschlüssen Basis, Kollektor und Emitter')}${note('Bauteil zuerst bestimmen','Die Pinfolge gilt nicht für jeden Transistor. Vergleiche die genaue Bezeichnung, Blickrichtung und das zugehörige Datenblatt. Auch Widerstand, Diode und Versorgung müssen zu eurem Motor passen.')}<p>Der Arduino liefert über einen <strong>Basiswiderstand</strong> das Steuersignal. Der große Motorstrom fließt im Hauptzweig. Er kommt nicht aus dem Arduino-Pin.</p>`,['Zeichne das verwendete Bauteil und beschrifte B, C und E. Notiere die genaue Bauteilbezeichnung.','Beschreibe den Unterschied zwischen Steuerzweig und Motorzweig in eigenen Worten.'],{solution:'<p>Der Steuerzweig führt vom Arduino-Ausgang über den Basiswiderstand zur Basis. Der Motorzweig führt von der passenden Versorgung durch Motor und Transistor zurück zur Versorgung. Der Transistor steuert diesen größeren Strom.</p>'}),
    step('wasser','Die Wasserventil-Analogie durchgehen',`<p>Das Arbeitsblatt vergleicht einen Transistor mit einem gesteuerten Ventil. Ein kleiner Steuerstrom beeinflusst ein Ventil, durch das ein größerer Hauptstrom fließen kann. Die Energie für den Hauptstrom liefert die Hauptversorgung.</p>${fig('transistor-wasser.png','Wasserventil-Modell mit kleinem Steuerstrom und größerem Hauptstrom')}${table(['Wassermodell','Elektrische Schaltung'],[['Kleiner Steuerzufluss','Basisstrom über einen Widerstand'],['Ventil','Steuerwirkung des Transistors'],['Hauptwasserstrom','Strom durch Motor und Transistor'],['Hauptversorgung','Passende Motorversorgung']])}<p>Eine Analogie hilft beim Vorstellen, hat aber Grenzen. Wasser ist kein elektrischer Strom. Ein Transistor erzeugt keine zusätzliche Energie und vervielfacht nicht die Leistung des Arduino-Pins.</p>`,['Zeichne ein einfaches Ventilmodell ins Heft und ordne die vier Teile der elektrischen Schaltung zu.','Schreibe einen Satz darüber, woher die Energie für den Motor tatsächlich kommt.']),
    step('schaltplan','Den vollständigen Motorzweig verfolgen',`<p>Verfolge zuerst den großen Strompfad: Plus der Motorversorgung → Motor → Kollektor → Emitter → Minus der Motorversorgung. Danach verfolgst du das Signal: Arduino-Ausgang → Basiswiderstand → Basis.</p>${fig('motor-schaltung.svg','Prinzip der Transistorschaltung: Motorversorgung, Motor, Freilaufdiode, TIP120, Basiswiderstand und gemeinsamer GND','Prinzipschaltbild zur Unterrichtsaufgabe. Bauteilwerte und Versorgung werden passend zum Schulmotor festgelegt.')}<p>Arduino-GND und Minus der Motorversorgung sind verbunden: Sie bilden einen <strong>gemeinsamen Bezug</strong>. Die Freilaufdiode liegt parallel zum Motor. Ihre <strong>Kathode K</strong>, meist mit Ring markiert, liegt an Plus; ihre <strong>Anode A</strong> liegt am Kollektor. Im normalen Betrieb sperrt sie und beim Abschalten fängt sie die induktive Spannungsspitze ab.</p><p>Die Motorversorgung kommt nicht an einen Signalpin. Trenne die Versorgung, bevor du Anschlüsse änderst. Lass den ausgefüllten Schaltplan vor dem Aufbau im Unterricht prüfen.</p>`,['Zeichne den Schaltplan ins Heft. Beschrifte B, C, E, Basiswiderstand, Motorversorgung, gemeinsamen GND und die Diode mit A und K.','Verfolge Steuerstrom und Motorstrom mit zwei Farben. Erkläre die Aufgabe der Freilaufdiode.'],{hints:['Die Diode zeigt mit ihrer Kathodenseite zum positiven Motoranschluss.','Gemeinsamer GND bedeutet einen gemeinsamen Spannungsbezug; die positive Motorversorgung wird dadurch nicht zum Arduino-Signal.'],solution:'<p>Der kleine Steuerstrom schaltet den Transistor. Der Motorstrom fließt aus der geeigneten Motorversorgung über den Motor und die C-E-Strecke zurück. Die korrekt gepolte Diode schützt den Schaltzweig beim Abschalten der induktiven Last.</p>'}),
    step('programm','Drei Sekunden an, fünf Sekunden aus',`<p>Erst nach dem geprüften Aufbau testest du die Schaltung mit einem kurzen Programm. Hier ist <strong>Pin 3</strong> das Steuersignal zum Basiswiderstand. LED-Pin 5 und Servo-Signalpin 8 bleiben für die anderen Teilfunktionen verfügbar.</p>${code('const int motorPin = 3;\n\nvoid setup() {\n  pinMode(motorPin, OUTPUT);\n  digitalWrite(motorPin, LOW);\n}\n\nvoid loop() {\n  digitalWrite(motorPin, HIGH); // Motorzweig einschalten\n  delay(3000);                // 3 Sekunden laufen lassen\n  digitalWrite(motorPin, LOW); // Motorzweig ausschalten\n  delay(5000);                // 5 Sekunden warten\n}')}<p>Ein loop-Durchlauf dauert ungefähr 8 Sekunden. Ein Motor kann nach dem Ausschalten noch auslaufen. Unterscheide daher das <strong>Steuersignal</strong> und die beobachtete mechanische Bewegung.</p><a href="code/motor.ino" download>Motor-Testprogramm herunterladen</a>`,['Schreibe den Ablauf von loop mit Zeitangaben ins Heft und kommentiere die vier entscheidenden Zeilen.','Notiere nach dem Versuch: Was hast du erwartet, was beobachtet und welche Ursache vermutest du bei einer Abweichung?'],{quiz:quiz('Wie lange ist das Motor-Steuersignal in jedem Durchlauf HIGH?',['3 Sekunden.','5 Sekunden.','8 Sekunden.'],0,'HIGH wird gesetzt und bleibt während delay(3000) bestehen. Danach folgen 5 Sekunden LOW. Zusammen sind es ungefähr 8 Sekunden.')}),
    step('motor-pwm','Die Ansteuerung mit PWM dosieren',`<p>Mit <code>analogWrite(3, wert)</code> kannst du an Pin 3 die Einschaltzeit der passenden Leistungsstufe ändern. Der Wert liegt hier zwischen 0 und 255. 128 entspricht ungefähr 50 % Einschaltzeit.</p>${code('analogWrite(3, 128); // ungefähr 50 % Einschaltzeit\ndelay(4000);         // 4 Sekunden beobachten\nanalogWrite(3, 0);   // ausschalten')}<p><strong>50 % Einschaltzeit bedeutet nicht sicher 50 % Drehzahl.</strong> Reibung, Last, Versorgung und das Verhalten des Motors spielen mit. Ein niedriger Wert reicht möglicherweise nicht zum Anlaufen. Die richtige Einstellung findest du durch Messungen.</p>`,['Skizziere ein PWM-Signal mit ungefähr 50 % Einschaltzeit und beschrifte HIGH, LOW und Zeit.','Plane einen Vergleich von drei PWM-Werten. Halte Versorgung und Last gleich und notiere die beobachtete Bewegung.'],{solution:'<p>Ein möglicher Vergleich nutzt die Werte 100, 180 und 255 bei derselben Last. Notiere, ob der Motor selbst startet und wie lange eine markierte Umdrehung dauert. Die Zahlen sind Versuchseinstellungen, keine zugesicherte Drehzahl.</p>'})
  );

  const gears={id:'getriebe',number:'06',title:'Getriebe und Lagerung',subtitle:'Bewegung passend übertragen',time:'ca. 2–3 Arbeitsphasen',source:'Arbeitsblatt Getriebe 1 + 2 V01 und Folien DC-Motor/Getriebe',intro:'Du erkennst Getriebearten, lagerst Achsen sinnvoll und rechnest aus, wie sich Drehzahl und Drehmoment verändern.',steps:[
    step('arten','Vier Getriebearten erkennen',`<p>Ein Getriebe überträgt Bewegung zwischen einem Antrieb und einem Abtrieb. Du kannst es an den Teilen erkennen, die die Bewegung weitergeben.</p>${fig('getriebe-arten.png','Vier Beispiele a bis d: Zahnräder, Reibrollen, Kette und Riemen')}${table(['Art','Woran du sie erkennst'],[['Zahnradgetriebe','Zähne greifen direkt ineinander.'],['Reibrollengetriebe','Rollen berühren sich und übertragen Bewegung durch Reibung.'],['Kettengetriebe','Eine Kette greift in die Zähne von Kettenrädern.'],['Riemengetriebe','Ein Riemen läuft über Scheiben; je nach Art durch Reibung oder Zahnkontakt.']])}`,['Zeichne eine Tabelle mit a, b, c und d ins Heft. Ordne jeweils Getriebeart und ein Erkennungsmerkmal zu.'],{solution:'<p>a: Zahnradgetriebe. b: Reibrollengetriebe. c: Kettengetriebe. d: Riemengetriebe.</p>'}),
    step('winkel-schnecke','Winkelgetriebe und Schneckengetriebe',`<p>Ein <strong>Winkelgetriebe</strong> kann die Bewegungsrichtung zwischen unterschiedlich ausgerichteten Achsen umlenken, zum Beispiel mit Kegelrädern. Bei einem <strong>Schneckengetriebe</strong> treibt eine schraubenförmige Schnecke ein Schneckenrad an.</p>${fig('winkel-schnecke.png','Schematische Darstellung von Schneckengetriebe und Winkelgetriebe')}<p>Die Schnecke kann eine große Untersetzung ermöglichen: Der Abtrieb dreht langsamer und hat im idealen Modell mehr Drehmoment. Manche Schneckengetriebe sind <strong>selbsthemmend</strong>: Der Abtrieb kann die Schnecke dann nicht leicht zurückdrehen. Das hängt von der Geometrie und Reibung ab und gilt nicht automatisch für jedes Schneckengetriebe.</p>`,['Skizziere beide Getriebearten und zeichne die Achsrichtungen ein.','Erkläre eine mögliche Anwendung der langsamen Bewegung und weshalb du Selbsthemmung am konkreten Getriebe prüfen musst.']),
    step('lager','Radiale und axiale Kräfte unterscheiden',`<p>Ein Lager führt eine Achse und lässt sie sich möglichst leicht drehen. <strong>Radial</strong> bedeutet quer zur Achse. <strong>Axial</strong> bedeutet entlang der Achse. Stell dir einen Fahrradreifen vor: Eine Kraft von oben ist radial, ein seitliches Verschieben des Rads auf der Achse ist axial.</p><div class="figure-grid">${fig('lager-radial.png','Kraftpfeil quer zur Achse: radial')}${fig('lager-axial.png','Kraftpfeil entlang der Achse: axial')}</div><p>Zwei ausreichend auseinanderliegende radiale Lagerstellen können eine Achse führen und ein Kippen begrenzen. Für unser Getriebegestell planst du deshalb zwei radiale Lagerstellen je Achse.</p>`,['Zeichne eine Achse mit zwei Lagerstellen. Zeichne je einen radialen und einen axialen Kraftpfeil ein.','Wie viele radiale Lagerstellen brauchst du im Schulmodell für fünf Achsen? Schreibe die Rechnung auf.'],{solution:'<p>5 Achsen · 2 Lagerstellen pro Achse = 10 radiale Lagerstellen. Radiale Pfeile stehen quer zur Achse; axiale Pfeile verlaufen längs.</p>'}),
    step('fest-los','Eine Achse mit Festlager und Loslager führen',`<p>Eine Achse soll sich drehen und gleichzeitig an der richtigen Stelle bleiben. Im Schulmodell übernimmt eine Lagerstelle die axiale Festlegung: das <strong>Festlager</strong>. Die andere führt radial, lässt aber den vorgesehenen axialen Ausgleich zu: das <strong>Loslager</strong>.</p>${fig('fest-los-lager.png','Achse mit zwei Lagerstellen und Stellringen zur axialen Festlegung')}<p>Wenn du beide Seiten ohne Spiel axial festklemmst, können ungenaue Abstände oder Wärmeausdehnung den Aufbau verspannen. Die Achse läuft dann schwer. Gleich angeordnete Festlager helfen dir, die Lage mehrerer Achsen von einer gemeinsamen Bezugseite aus aufzubauen.</p>`,['Markiere in deiner Achsskizze ein Festlager und ein Loslager. Erkläre, welche Bewegungen jeweils geführt oder begrenzt werden.','Plane die Fest- und Loslager für fünf Achsen und erkläre, warum du nicht beide Seiten axial festklemmst.'],{solution:'<p>Bei der hier verwendeten Anordnung sind es 5 Festlager und 5 Loslager, insgesamt 10 radiale Lagerstellen. Jede Achse wird axial an einer Stelle festgelegt. Die andere Stelle ermöglicht den vorgesehenen Ausgleich.</p>'}),
    step('bohrung','Warum eine Stufenbohrung helfen kann',`<p>Bei der gezeigten Stufenbohrung ist nur ein kurzer Abschnitt so eng, dass er die Achse führt. Der übrige Abschnitt ist weiter. So berührt eine schiefe oder ungenau gebohrte Wand die Achse nicht über die gesamte Dicke.</p>${fig('stufenbohrung.png','Querschnitt einer Bohrung mit kurzem engen Führungsabschnitt und weiterem Abschnitt')}<p>Das kann das Klemmen und unerwünschtes Reiben im Holzgestell verringern. Es ersetzt weder eine fluchtende Ausrichtung noch passende Abstände. Behaupte nicht allgemein, dass Reibung allein wegen einer kleineren Kontaktfläche immer kleiner sein muss.</p>`,['Skizziere eine einfache und eine abgestufte Bohrung im Querschnitt. Markiere den führenden Abschnitt.','Formuliere eine Prüfliste mit drei Punkten, damit eure Achse leicht läuft.'],{hints:['Prüfe Ausrichtung der Lagerstellen, genügend Spiel und die Stellung der Stellringe.']}),
    step('formel','Das Übersetzungsverhältnis berechnen',`<p>Wir nennen den Antrieb 1 und den Abtrieb 2. Das Übersetzungsverhältnis <strong>i</strong> vergleicht ihre Drehzahlen:</p><div class="formula">i = n₁ / n₂ = z₂ / z₁</div><p><strong>n</strong> ist die Drehzahl, <strong>z</strong> die Zahnzahl. Bei passenden Zahnrädern ist auch das Verhältnis der <strong>Teilkreisdurchmesser</strong> d₂/d₁ gleich i. Miss dafür nicht einfach den äußeren Rand mit Zahnspitzen.</p>${table(['Fall','Drehzahl am Abtrieb','Ideales Drehmoment'],[['i &gt; 1','Kleiner: Untersetzung','Größer'],['i = 1','Gleich groß','Gleich groß'],['i &lt; 1','Größer: Übersetzung ins Schnelle','Kleiner']])}<p>Beispiel: z₁ = 10 und z₂ = 30 ergeben i = 3. Bei n₁ = 120 U/min folgt n₂ = 120/3 = 40 U/min.</p>`,['Schreibe die Formel mit Erklärung der Größen ins Heft.','Berechne für z₁ = 12, z₂ = 36 und n₁ = 180 U/min zuerst i und dann n₂.'],{widget:'gear',hints:['Teile die Abtriebszahnzahl durch die Antriebszahnzahl. Danach teilst du die Eingangsdrehzahl durch i.'],solution:'<p>i = 36/12 = 3. n₂ = 180/3 = 60 U/min. Eine Umdrehung dauert 60/60 = 1 s.</p>'}),
    step('drehmoment','Drehmoment: die Drehwirkung einer Kraft',`<p>Eine Kraft dreht besonders wirksam, wenn sie einen großen Hebelarm zur Achse hat. Für eine senkrecht am Hebel wirkende Kraft gilt:</p><div class="formula">M = F · r</div><p><strong>M</strong> ist das Drehmoment in Newtonmeter (Nm), <strong>F</strong> die Kraft in Newton und <strong>r</strong> der senkrechte Hebelarm in Meter. Eine Kraft von 2 N an einem Hebelarm von 0,05 m erzeugt 0,10 Nm.</p><p>Ein ideales Getriebe mit i = 3 macht die Drehzahl dreimal kleiner und das Drehmoment dreimal größer. Es erzeugt dadurch keine zusätzliche Leistung: langsamer drehen und stärker drehen gleichen sich im idealen Modell aus. Reale Getriebe haben Verluste.</p>`,['Rechne das Drehmoment von 4 N bei einem senkrechten Hebelarm von 3 cm aus. Achte auf Meter als Längeneinheit.','Ein idealer Antrieb liefert 0,02 Nm. Welches Abtriebsdrehmoment ergibt i = 4? Beschreibe gleichzeitig die Drehzahländerung.'],{solution:'<p>3 cm = 0,03 m. M = 4 N · 0,03 m = 0,12 Nm. Beim idealen Getriebe: M₂ = 4 · 0,02 Nm = 0,08 Nm; n₂ = n₁/4. Durch Verluste steht praktisch weniger Drehmoment zur Verfügung.</p>'}),
    step('fahrrad','Am Fahrrad bergauf und bergab denken',`<p>Beim Fahrrad ist das vordere Kettenblatt der Antrieb und das hintere Ritzel der Abtrieb. Eine offene Kette überträgt die Drehrichtung gleichsinnig. Sie verhält sich dabei anders als zwei direkt ineinandergreifende Zahnräder.</p>${fig('fahrrad-gaenge.png','Fahrrad beim Bergauffahren und Bergabfahren mit verschiedenen Kettenradgrößen')}<p>Bergauf wählst du typischerweise vorne ein kleineres und hinten ein größeres Zahnrad. Dadurch wird der Abtrieb im Verhältnis zur Tretbewegung langsamer; du erhältst mehr Drehmoment. Für schnelles Fahren wählst du typischerweise vorne groß und hinten klein.</p>`,['Zeichne für bergauf und für schnelles Fahren je eine sinnvolle Kettenführung zwischen den vorgegebenen Radgrößen ins Heft.','Berechne i bei vorne 20 und hinten 40 Zähnen sowie bei vorne 40 und hinten 20 Zähnen. Erkläre den Unterschied.'],{solution:'<p>Bergauf: i = 40/20 = 2, der Abtrieb ist langsamer. Schnell: i = 20/40 = 0,5, der Abtrieb ist schneller. Das Modell beschreibt die Übertragung zwischen den Kettenrädern.</p>'}),
    step('stufen','Mehrere Getriebestufen zusammenrechnen',`<p>Bei einem mehrstufigen Getriebe berechnest du jede Stufe einzeln. Die Gesamtübersetzung ist das Produkt der Teilübersetzungen:</p><div class="formula">i<sub>gesamt</sub> = i₁ · i₂ · …</div><p>Beispiel: In Stufe 1 treibt ein 10-Zähne-Rad ein 30-Zähne-Rad an. Auf derselben Abtriebsachse sitzt ein 12-Zähne-Rad, das in Stufe 2 ein 24-Zähne-Rad antreibt. i₁ = 3 und i₂ = 2, also i_gesamt = 6.</p>${fig('getriebe-aufgaben.png','Getriebebeispiele aus dem Arbeitsblatt: Zahnradstufen und Schneckengetriebe')}<p>Zähle bei euren Zahnrädern die Zähne oder nutze ihre Kennzeichnung. Bei einer Schnecke brauchst du auch die <strong>Gangzahl</strong>: i = Zahnzahl des Schneckenrads / Gangzahl der Schnecke. Nur bei einer eingängigen Schnecke steht im Nenner 1.</p>`,['Zeichne das Zahlenbeispiel mit beiden Stufen und gemeinsamer Zwischenachse ins Heft. Berechne n₂ bei einer Eingangsdrehzahl von 240 U/min.','Bearbeite die Getriebebeispiele aus Aufgabe 2 des Arbeitsblatts. Notiere erst Zahnzahlen und gegebenenfalls Gangzahl; rechne danach die Gesamtübersetzung.'],{hints:['Räder auf derselben starren Achse haben dieselbe Drehzahl.','Ein zusätzliches Zwischenrad zwischen zwei äußeren Zahnrädern verändert die Drehrichtung, aber bei einer einfachen Kette nicht das Verhältnis der ersten und letzten Zahnzahl.'],solution:'<p>i_gesamt = (30/10) · (24/12) = 6. n_aus = 240/6 = 40 U/min. Bei den Bildaufgaben hängt das Zahlenresultat von den tatsächlich gezählten Zähnen und der Gangzahl ab.</p>'}),
    step('drehrichtung','Die Drehrichtung Schritt für Schritt verfolgen',`<p>Beginne bei der Kurbel. Zeichne für jedes Bauteil zuerst einen Pfeil und gehe dann zur nächsten Verbindung. So verlierst du bei mehreren Übertragungen nicht den Überblick.</p>${table(['Verbindung','Regel'],[['Zwei äußere Zahnräder oder berührende Reibrollen','Drehrichtung kehrt sich um.'],['Räder auf derselben starren Achse','Gleiche Drehrichtung bei gleicher Blickrichtung.'],['Offene Kette oder offener Riemen','Gleichsinnige Drehung bei parallelen Achsen und gleicher Blickrichtung.'],['Gekreuzter Riemen','Gegensinnige Drehung.'],['Kegelrad oder Schnecke','Achsrichtung und Eingriff räumlich beachten.']])}${fig('getriebe-drehrichtung.png','Zusammengesetztes Getriebe mit Kurbel, Zahnrädern, Kette, Riemen und Zahnstange')}<p>Bei der räumlichen Darstellung musst du die Blickrichtung dazuschreiben. „Im Uhrzeigersinn“ kann von der anderen Achsseite betrachtet umgekehrt aussehen. Bei einer Zahnstange gibt der Kontaktpunkt an, ob sie sich nach links oder rechts bewegt.</p>`,['Zeichne die Übertragung aus Aufgabe 3 ins Heft und trage die Bewegungsrichtung an jedem Bauteil ein. Beschrifte deine Blickrichtung.','Prüfe zuerst Zahnradpaar, offene Kette und offenen Riemen mit den Regeln. Kläre die räumlichen Eingriffe am Modell oder mit der Lehrkraft.'],{hints:['Gehe Verbindung für Verbindung vor. Nutze an jedem Kontaktpunkt die Bewegung der Oberfläche.'],solution:'<p>Das erste äußere Zahnradpaar kehrt die Drehrichtung um. Die offene Kette und der offene Riemen übertragen sie gleichsinnig. Räder auf derselben starren Achse behalten dieselbe Winkelbewegung. Für die letzte räumliche Übertragung prüfst du den gezeigten Eingriff und deine Blickrichtung am Modell.</p>'})
  ]};
  COURSE.splice(COURSE.findIndex(m=>m.id==='statik'),0,gears);
  chapter('statik').number='07';chapter('blasen').number='08';chapter('projekt').number='09';
  chapter('statik').source='Arbeitsblatt Statik V4, Statik-Folien und Kahoot-Tabelle Statik';
  const area=chapter('statik').steps.find(s=>s.id==='zug-flaeche');
  area.body=`<p>In der neuen Fassung <strong>Statik V4</strong> wird der Faden einfach, zweifach, dreifach und vierfach verwendet. Mehr parallel belastete Fäden vergrößern die gesamte Querschnittsfläche. Material und freie Länge bleiben für einen fairen Vergleich gleich.</p><p>Übernimm die Messwerttabelle in dein Heft. Addiere je Reihe die drei Reißkräfte und teile durch 3. Schreibe den Rechenweg und den Mittelwert mit der Einheit Newton auf. Runde auf zwei Nachkommastellen.</p><p>Zeichne danach ein Diagramm: Fadenzahl beziehungsweise relative Querschnittsfläche auf der x-Achse, mittlere Reißkraft in N auf der y-Achse. Nutze Messpunkte und prüfe, ob eine steigende Ausgleichsgerade die Daten sinnvoll beschreibt.</p>${note('Welche Werte verwenden wir?','Website und PDF nutzen dieselbe neue Messreihe aus Statik V4. Die früheren auffälligen Angaben wurden durch diese ausdrücklich bereitgestellte Fassung ersetzt.')}`;
  area.fields=[{key:'0',label:'Aufgabe 2b: Beschreibe den Zusammenhang zwischen Fadenzahl und mittlerer Reißkraft. Vergleiche auch die Streuung innerhalb der Messreihen.'},{key:'1',label:'Aufgabe 2c: Wie würde ein zugfesteres Material bei gleichem Querschnitt dein Diagramm verändern?'}];
  area.hints=['Je mehr parallel belastete Fäden, desto mehr Material trägt die Last.','Formuliere die Regel zur Reißkraft in Newton. Die Material-Zugfestigkeit ist eine andere, auf die Fläche bezogene Größe.'];
  area.solution='<p>Die Mittelwerte aus Statik V4 sind 9,90 N; 19,97 N; 27,00 N und 39,93 N. Insgesamt steigt die mittlere Reißkraft ungefähr mit der Fadenzahl beziehungsweise Querschnittsfläche. Reale Messwerte streuen. Ein zugfesteres Material könnte bei gleichem Querschnitt höhere Reißkräfte ergeben; der Graph läge typischerweise höher.</p>';
  const span=chapter('statik').steps.find(s=>s.id==='spannweite');
  span.body+=`<h3>Spannweite und lichte Weite unterscheiden</h3><p>Die Spannweite beziehungsweise Stützweite ist der Abstand der maßgeblichen Auflagerpunkte, bei gleichartigen Lagern meist ihrer Mittellinien. Die <strong>lichte Weite</strong> ist der freie Abstand zwischen den inneren Rändern der Auflager. Zeichne beide Strecken getrennt ein; sie sind bei breiten Auflagern nicht gleich groß.</p>`;
  span.fields.push({key:'2',label:'Zeichne einen Balken auf zwei breiten Auflagern. Markiere Spannweite l und lichte Weite l′ mit unterschiedlichen Farben.'});
  chapter('statik').steps.push(step('modell-rechnen','Die Balkenformel mit drei Vergleichen nutzen',`<p>Du hast das Modell w ∝ l³/(b · h³) kennengelernt. Rechne jetzt mit einem frei gewählten <strong>Übungswert</strong>: Ein Ausgangsbalken biegt sich unter der festgelegten Last um 8 mm durch. Werkstoff, Last und Auflagerung bleiben gleich.</p>${table(['Änderung','So setzt du den Faktor ein'],[['Nur doppelte Spannweite','2³ = 8 im Zähler'],['Nur doppelte Breite','2 im Nenner'],['Nur doppelte Höhe','2³ = 8 im Nenner']])}<p>Rechne immer jede Änderung vom Ausgangsbalken aus. Mische nicht versehentlich die Ergebnisse mehrerer Varianten.</p>`,['Berechne die Durchbiegung für jede der drei Varianten. Schreibe Rechenweg und Einheit ins Heft.','Welche Änderung hilft am stärksten gegen Durchbiegung? Nenne außerdem eine konstruktive Grenze dieser Änderung.'],{solution:'<p>Doppelte Spannweite: 8 mm · 8 = 64 mm. Doppelte Breite: 8 mm / 2 = 4 mm. Doppelte Höhe: 8 mm / 8 = 1 mm. Mehr Höhe hilft stark, benötigt aber Platz und eine passende seitliche Führung. Die Werte sind Modellrechnungen, keine real gemessenen Schulwerte.</p>'}),step('quiz','Statik-Selbstcheck: 15 Fragen',`<p>Die Quizfragen aus deiner Statik-Tabelle helfen dir, Belastungsarten und Konstruktionsregeln zu unterscheiden. Jede geprüfte Antwort erhält eine Erklärung. Nimm dir Zeit und verbessere bei Bedarf auch deinen Merksatz im Heft.</p>`,['Wähle zwei Regeln aus dem Quiz aus. Erkläre im Heft, wie du sie an deiner Seifenblasenmaschine anwenden kannst.'],{widget:'quiz-statik'}));

  const bubbles=chapter('blasen');bubbles.source='Arbeitsblatt Seifenblasenlösung und Projektfolien; ergänzende Versuchsführung';
  bubbles.steps.push(
    step('rezepte','Zwei Startrezepte kennenlernen',`<p>Das neue Arbeitsblatt nennt zwei Startrezepte. Ein Startrezept ist eine erste Variante zum Testen. Es ist noch kein garantiert bestes Rezept für euren Ring und Luftstrom.</p>${table(['Bestandteil','Rezept 1','Rezept 2'],[['Destilliertes Wasser','350 mL','350 mL'],['Spülmittel beziehungsweise Shampoo','100 mL Spülmittel','100 mL Shampoo'],['Zucker','50 g Traubenzucker','25 g Puderzucker']])}<p>Für eine kleine Probe könnt ihr nach Absprache <strong>ein Fünftel</strong> ansetzen:</p>${table(['Bestandteil','Kleine Probe 1','Kleine Probe 2'],[['Destilliertes Wasser','70 mL','70 mL'],['Spülmittel beziehungsweise Shampoo','20 mL Spülmittel','20 mL Shampoo'],['Zucker','10 g Traubenzucker','5 g Puderzucker']])}<p>mL ist eine Volumeneinheit; g ist eine Masseneinheit. Die Angaben sind Zutatenmengen, keine zugesicherte Endmenge. Die beiden Originalrezepte ändern mehrere Bestandteile zugleich. Ihr könnt ihren Gesamterfolg vergleichen, aber daraus nicht die Wirkung einer einzelnen Zutat ableiten.</p>${note('Proben zuordnen','Beschrifte Becher und feste Abstellplätze mit A, B, C und D. Halte Lösung von Elektronik fern, vermeide Augenkontakt und trinke sie nicht. Wische verschüttete Lösung weg.')}`,['Übernimm beide Startrezepte mit Einheiten ins Heft. Zeige für eine Zutat die Rechnung zum Verkleinern auf ein Fünftel.','Wählt ein Startrezept und begründet eure Entscheidung. Notiert die tatsächlich verwendeten Produkte und Mengen.'],{solution:'<p>Beispiel Wasser: 350 mL / 5 = 70 mL. Spülmittel: 100 mL / 5 = 20 mL. Für Rezept 1: 50 g / 5 = 10 g. Die Wahl des Rezepts muss durch eure Versuche geprüft werden.</p>'}),
    step('vier-becher','Mit vier Bechern gezielt verbessern',`<p>Das Arbeitsblatt gibt euch vier Probebecher. Nutze A als Vergleichsprobe. Bei B, C und D veränderst du <strong>jeweils nur dieselbe eine Einflussgröße</strong>, zum Beispiel die Zuckermenge. Wasser, Spülmittel, Ring, Luftstrom und Testort bleiben gleich.</p><p>Notiere alle Mengen vor dem Mischen. Rühre nach derselben Methode und lasse die Proben gleich lange stehen. Nutze einen einfachen Testdispenser und immer dasselbe Verfahren zum Benetzen.</p>${table(['Probe','Zweck','Was wird festgehalten?'],[['A','Startrezept als Vergleich','Alle Zutaten und Bedingungen'],['B','Eine kleinere Einstellung','Nur die gewählte Größe ändern'],['C','Eine zweite Einstellung','Alle anderen Bedingungen gleich halten'],['D','Eine dritte Einstellung','Alle anderen Bedingungen gleich halten']])}<p>Die konkreten Einstellungen legt ihr mit der Versuchsanweisung fest. Vergleiche erst nach mindestens drei Versuchen je Probe.</p>`,['Lege im Heft einen Versuchsplan mit A bis D an. Notiere Vermutung, veränderte Größe und alle konstanten Bedingungen.','Zeichne eure vier festen Abstellplätze und beschrifte sie eindeutig.'],{hints:['Wenn du die Zuckermenge untersuchst, ändere nicht gleichzeitig die Spülmittelmarke oder das Wasser.']}),
    step('protokoll','Ein vollständiges Misch- und Testprotokoll führen',`<p>Ein anderer Mensch soll deine Mischung nachmachen und den Test verstehen können. Darum reicht „etwas mehr Zucker“ als Eintrag nicht aus.</p>${table(['Im Heft festhalten','Beispiel einer genauen Angabe'],[['Probe und Rezept','A, Produktname, Zutaten mit mL und g'],['Mischen','Reihenfolge, Rührdauer und Standzeit'],['Versuchsaufbau','Ringform, Abstand, Motoransteuerung, Testort'],['Messwerte','Durchmesser und Schwebezeit für Versuch 1, 2 und 3'],['Ergebnis','Mittelwerte, Streuung, Fehlversuche und Entscheidung']])}<p>Miss die Schwebezeit ab dem Ablösen. Verwende für den Durchmesser möglichst dieselbe Vergleichsskala. Protokolliere auch, wenn sich gar keine Blase ablöst.</p>`,['Lege ein Mischprotokoll im Heft an und dokumentiere jede Probe vollständig.','Zeichne eine Ergebnistabelle: Probe | Durchmesser 1–3 / cm | Schwebezeit 1–3 / s | Fehlversuche | Beobachtung. Fülle sie während des Versuchs aus.']),
    step('optimieren','Größe, Haltbarkeit und Schwebezeit zusammen bewerten',`<p>Das Arbeitsblatt stellt die Spannung zwischen großen, haltbaren Blasen und langer Schwebezeit heraus. Ein stabiler Film kann helfen, eine große Blase zu bilden. Ein schwererer Film kann die Bewegung beeinflussen. Daraus folgt aber keine feste Regel, dass jede dickere Blase immer schneller fällt.</p><p>Auch Luftbewegung, Temperatur, Luftfeuchtigkeit, Blasengröße und der Aufbau beeinflussen eure Beobachtung. Entscheide deshalb anhand der <strong>gemessenen Ergebnisse</strong>. Die größte Blase gewinnt nicht automatisch, wenn sie die nötige Schwebezeit verfehlt.</p><ol><li>Vergleiche die Wiederholungen jeder Probe.</li><li>Prüfe, welche Proben 7 cm und 8 s erreichen.</li><li>Bewerte auch die Zuverlässigkeit.</li><li>Wähle eine Variante und begründe sie mit Messwerten.</li><li>Teste sie anschließend in der vollständigen Maschine.</li></ol>`,['Berechne die mittleren Durchmesser und Schwebezeiten eurer gelungenen Versuche. Gib zusätzlich die Zahl der Fehlversuche an.','Wähle eure Lösung anhand der Projektkriterien. Begründe mit Zahlen und nenne eine noch offene Unsicherheit.'],{hints:['Ein Mittelwert verschweigt, ob drei Versuche ähnlich waren oder stark streuten. Notiere deshalb auch die Einzelwerte.'],solution:'<p>Eine begründete Wahl könnte lauten: „Probe B erreicht in drei von drei Tests beide Grenzen. Probe C bildet zwar größere Blasen, erreicht aber nur einmal 8 s. Wir testen B im Gesamtsystem.“ Dies ist ein Formulierungsbeispiel, keine vorgegebene Messreihe.</p>'})
  );

  const project=chapter('projekt');project.source='Projektfolien, Arbeitsplan, Meilensteinplan, Projektmanagement-Checkliste und Reflexionsbogen';
  project.steps[0].body=`<p>Nutzt eure Systemanalyse und legt einen konkreten Aufbau fest. Die neueren Projektfolien nennen folgenden Materialrahmen:</p>${table(['Teil','Vorgabe'],[['Dispenser','2 Pfeifenreiniger'],['Turm','30 Holzstäbe'],['Bewegung','1 Positionsservo und 1 DC-Motor'],['Steuerung','1 Arduino, Kabel und Steckbrett'],['Antrieb und Aufbau','1 Luftschraube, Getriebe, Holz und Schnur']])}<p>Klärt Behälter, passende Stromversorgung, Motoransteuerung, Befestigungsteile und genaue Ausführung mit eurer Lehrkraft. Die früheren Folien nennen teilweise einen anderen Materialstand; für euer Projekt gilt die aktuelle Unterrichtsabsprache.</p><p>Erstellt eine beschriftete Konstruktionsskizze, eine Pin- und Anschlussliste sowie einen Ablaufplan. Beschreibt, wie ein Tastendruck genau einen geplanten Durchlauf startet.</p>`;
  project.steps.find(s=>s.id==='abschluss').body=project.steps.find(s=>s.id==='abschluss').body.replace(/<div class="callout "><strong>Lernheft sichern<\/strong>[\s\S]*?<\/div>/,note('Deine Ergebnisse abgeben','Prüfe dein handschriftliches Heft: Überschriften, Skizzen, Rechnungen, Messwerte und Reflexion sollen vollständig sein. Gib Heft, Maschine und weitere Unterlagen so ab, wie ihr es im Unterricht vereinbart habt.'));
  project.steps.push(
    step('arbeitsplan','Einen Arbeitsplan mit echten Arbeitspaketen anlegen',`<p>Das neue Arbeitsblatt trennt die geplante Verantwortung vom tatsächlichen Abschluss. Ein Arbeitspaket soll ein sichtbares, prüfbares Ergebnis liefern. „Halterung passt zum Servo und bewegt den Ring ohne Klemmen“ ist genauer als „Mechanik machen“.</p>${table(['Arbeitspaket','Wer ist verantwortlich?','Wann erledigt?','Von wem erledigt?'],[['Ringhalter bauen und testen','Im Team festlegen','Nach Abschluss eintragen','Tatsächliche Mitarbeit eintragen'],['Motorzweig aufbauen und prüfen','Im Team festlegen','Nach Abschluss eintragen','Tatsächliche Mitarbeit eintragen']])}<p>Die linke Hälfte füllt ihr vor der Arbeit aus. Die rechte Hälfte ergänzt ihr nach dem Abschluss. Teilt die Arbeit fair auf und wechselt die Tätigkeiten, damit jede Person auch konstruieren, programmieren, testen und dokumentieren lernt.</p><a href="material/Arbeitsplan.pdf" target="_blank" rel="noopener">Arbeitsplan als PDF öffnen</a>`,['Schreibe die Überschrift „Projekt · Arbeitsplan“ und zeichne die vier Spalten ins Heft. Plane mindestens fünf konkrete Arbeitspakete mit verantwortlichen Personen.','Markiere, welche Pakete erst beginnen können, wenn ein anderes Ergebnis vorliegt. Ergänze nach jeder Arbeitsphase die tatsächlichen Abschlüsse.'],{hints:['Vor dem Aufbau muss das Material da sein. Vor dem Gesamttest müssen die einzelnen Teilfunktionen funktionieren.']}),
    step('meilensteine','Meilensteine als überprüfbare Zwischenziele festlegen',`<p>Ein Meilenstein ist ein wichtiges erreichtes Ergebnis. Er heißt zum Beispiel „Alle Teilfunktionen sind einzeln getestet“ und nicht bloß „Weiterbauen“. Ein Soll-Termin ist euer Plan; der Ist-Termin ist der tatsächliche Abschluss.</p>${table(['Möglicher Meilenstein','Woran ihr ihn erkennt'],[['Entwurf steht','Systembild, Ablauf und Material sind geklärt.'],['Antriebe funktionieren','Servo und DC-Motor sind einzeln geprüft.'],['Konstruktion steht','Lagerung und Stabilität sind überprüft.'],['Erste Blase entsteht','Der vollständige Ablauf funktioniert.'],['Gesamttest abgeschlossen','Messwerte zu allen Projektkriterien liegen vor.'],['Abgabe bereit','Maschine, Dokumentation und Reflexion sind vollständig.']])}<p>Tragt die aktuellen Unterrichtstermine ein. Die alten Datumsangaben der Folien gelten nicht automatisch. Plant Zeit für Fehlersuche, Wiederholungen und Verbesserung ein.</p><a href="material/Meilensteine.pdf" target="_blank" rel="noopener">Meilensteinplan als PDF öffnen</a>`,['Lege im Heft die Tabelle „Meilenstein | Soll-Termin | Ist-Termin“ an. Vereinbart mindestens fünf überprüfbare Meilensteine.','Beschreibe, welcher nächste Termin gefährdet wäre, wenn ein früher Meilenstein verspätet erreicht wird.'],{solution:'<p>Wenn die Motoransteuerung später fertig wird, kann sich der Gesamttest verschieben. Ihr könnt währenddessen zum Beispiel die Dokumentation oder die Seifenlösung weiterbearbeiten. Die Termine werden bei der nächsten Teamsitzung angepasst.</p>'}),
    step('teamsitzung','Die fünf Minuten am Stundenanfang nutzen',`<p>Beginnt jede Doppelstunde mit einer kurzen Teamsitzung. Öffnet dazu Arbeitsplan, Meilensteine und die letzten Versuchseinträge. Entscheidet anhand dieser Unterlagen, was heute wirklich nötig ist.</p><ol><li><strong>1 Minute Rückblick:</strong> Was ist fertig, was belegen unsere Tests?</li><li><strong>1 Minute Ziel:</strong> Welches überprüfbare Ergebnis erreichen wir heute?</li><li><strong>1 Minute Aufgaben:</strong> Wer übernimmt was und wer arbeitet zusammen?</li><li><strong>1 Minute Hindernisse:</strong> Welches Material oder welche Hilfe fehlt?</li><li><strong>1 Minute Dokumentation:</strong> Was muss am Ende im Heft und im Plan stehen?</li></ol><p>Wenn ein Paket länger dauert, aktualisiert den Plan. Eine ehrliche Änderung ist hilfreicher als ein längst überholter Termin.</p>`,['Schreibe „Projekt · Teamsitzung“ mit Datum ins Heft. Notiere Ziel, Aufgabenverteilung, Hindernisse und die geplanten Nachweise.','Prüfe am Stundenende, was tatsächlich erreicht wurde. Aktualisiere Arbeitsplan und Meilensteine.']),
    step('abgabe','Die Unterlagen vollständig zusammenstellen',`<p>Die Projektfolien verlangen eine nachvollziehbare Dokumentation. Nutze diese Liste gemeinsam mit eurem Heft. Beschriftet die Unterlagen so, dass die Lehrkraft erkennt, welche Fassung zur fertigen Maschine gehört.</p>${table(['Unterlage','Prüffrage'],[['Programmablaufplan','Sind Start, Benetzen, Positionieren, Luftstrom und Rückkehr verständlich?'],['Arduino-Programm','Stimmen Pins und Kommentare mit der Maschine überein?'],['Schaltplan','Sind Versorgung, gemeinsamer GND, Ansteuerung und Schutzbauteile eingezeichnet?'],['Seifenlösungs-Protokoll','Sind Zutaten, Bedingungen und Ergebnisse nachvollziehbar?'],['Skizzen und Versuchseinträge','Sind Entscheidungen und Verbesserungen mit Beobachtungen belegt?'],['Arbeitsplan und Meilensteine','Sind Soll- und tatsächlicher Stand erkennbar?'],['Reflexion','Sind technische Bewertung, Zusammenarbeit und eigener Beitrag enthalten?']])}<p>Die Maschine selbst gehört ebenfalls zur vereinbarten Abgabe. Klärt Termin und Abgabeform im Unterricht.</p>`,['Erstelle im Heft eine Abgabeliste. Hake vorhandene Unterlagen ab und notiere fehlende Teile mit Zuständigkeit.','Vergleiche die Pinliste und den Schaltplan mit der tatsächlich gebauten Maschine. Notiere jede notwendige Korrektur.'])
  );
  COURSE.push({id:'reflexion',number:'10',title:'Rückblick und Reflexion',subtitle:'Ergebnisse erklären und daraus lernen',time:'ca. 45–60 Min.',source:'Reflexionsbogen Seifenblasenmaschine',intro:'Du beurteilst die technische Lösung und die Zusammenarbeit. Dein persönlicher Hefttext zeigt, was du selbst gelernt und beigetragen hast.',steps:[
    step('ziele','1 und 2: Zielerreichung und gelungene Lösungen',`<p>Beginne mit euren Messwerten aus dem Gesamttest. Trenne die Frage „Hat es funktioniert?“ von „Warum hat es funktioniert?“. Eine gute Erklärung verbindet eine technische Entscheidung mit einer beobachteten Wirkung.</p><p>Beispiel: Ein langsam bewegter Ring bleibt lange genug in der Lösung und erreicht wiederholt die richtige Position. Nenne dafür den verwendeten Antrieb, die Einstellung und eure Beobachtung.</p><a href="material/Reflexionsbogen.pdf" target="_blank" rel="noopener">Reflexionsbogen als PDF öffnen</a>`,['1. Zielerreichung: Prüfe Tastendruck, höchstens 15 s, mindestens 7 cm und mindestens 8 s anhand eurer Messwerte. Erkläre, warum ein nicht erreichtes Kriterium verfehlt wurde.','2. Funktionsanalyse: Welche technische Lösung hat besonders gut funktioniert? Erkläre physikalisch oder technisch, warum.']),
    step('probleme','3 und 4: Probleme und gezielte Verbesserungen',`<p>Beschreibe ein konkretes Problem, statt nur „Die Elektronik war schwierig“ zu schreiben. Nenne Beobachtung, mögliche Ursache und euren Test. Betrachte Mechanik, Elektronik, Stabilität, Blasenqualität und Zeitsteuerung.</p><p>Danach planst du eine Verbesserung für die gedachte Situation, dass ihr noch <strong>zwei Doppelstunden</strong> Zeit hättet. Beschreibe die technische Umsetzung und eine Messung, die zeigt, ob sie geholfen hat.</p>`,['3. Schwachstellen: Beschreibe ein konkretes technisches Problem, seine vermutete oder geprüfte Ursache und den dazugehörigen Versuch.','4. Optimierung: Was würdest du in zwei weiteren Doppelstunden ändern? Erkläre Umsetzung, erwartete Wirkung und Prüfmethode.'],{hints:['„Wir erhöhen den Turm“ braucht zusätzlich eine Begründung, einen Stabilitätscheck und einen Vergleich der Schwebezeit.']}),
    step('zusammenarbeit','5 und 6: Arbeitsteilung und Projektplanung',`<p>Bewerte eure Aufgabenverteilung mit Beispielen aus dem Arbeitsplan. Eine faire Verteilung bedeutet auch, dass alle Personen fachlich lernen und wissen, wie die Maschine funktioniert.</p><p>Schau anschließend auf die fünf Minuten am Stundenanfang. Haben sie geholfen, ein konkretes Ziel zu verfolgen? Konntet ihr Hindernisse rechtzeitig erkennen? Vergleiche Plan und tatsächlichen Verlauf.</p>`,['5. Zusammenarbeit: Bewerte eure Aufgabenverteilung als sehr gut, gut, teilweise passend oder schwierig. Begründe mit einem konkreten Beispiel.','6. Projektmanagement: Wie sinnvoll habt ihr die Planungsphase genutzt? Nenne eine Sache, die ihr beim nächsten Projekt besser planen würdet.']),
    step('kommunikation','7: Mit Problemen und Meinungsverschiedenheiten umgehen',`<p>Teams müssen Entscheidungen treffen. Eine sachliche Begründung und ein kleiner Vergleichstest können helfen, zwei Ideen zu prüfen. Beschreibe einen Vorgang, ohne einzelne Personen abzuwerten.</p><p>Auch gelungene Zusammenarbeit gehört in den Rückblick: Habt ihr einander eine Schaltung erklärt, gemeinsam einen Fehler eingegrenzt oder eine Aufgabe rechtzeitig übergeben?</p>`,['7. Kommunikation: Wie seid ihr mit Problemen oder unterschiedlichen Ideen umgegangen? Beschreibe ein konkretes Vorgehen.','Was habt ihr als Team gut gemacht und was wollt ihr bei der nächsten Zusammenarbeit beibehalten?']),
    step('persoenlich','8: Was habe ich selbst gelernt und erledigt?',`<p>Diesen Teil schreibt <strong>jede Person selbst</strong>. Auch wenn ihr gemeinsam gebaut habt, sind eure Erfahrungen unterschiedlich. Nenne ein technisches Lernziel und etwas, das du über Zusammenarbeit gelernt hast.</p><p>Beschreibe deinen Beitrag genau. „Am Motor gearbeitet“ ist unklar. „Den Motorzweig im Schaltplan gezeichnet, GND geprüft und drei PWM-Einstellungen verglichen“ zeigt, was du tatsächlich getan hast.</p>${note('Zum Abschluss','Prüfe die Überschriften und die Vollständigkeit deines Hefts. Markiere diesen Schritt erst, wenn dein persönlicher Rückblick geschrieben ist.')}`,['8. Persönliche Lernreflexion: Was habe ich technisch neu gelernt? Erkläre es mit einem Beispiel.','Was habe ich über Zusammenarbeit gelernt?','Welche Aufgaben habe ich hauptsächlich erledigt? Nenne möglichst genau Ergebnis, Arbeitsschritte und Tests.'])
  ]});

  // Die Inhalte folgen dem Arbeitsablauf: verstehen, planen, aufbauen, testen, auswerten.
  const reorder=(m,ids)=>{m.steps=ids.map(id=>m.steps.find(s=>s.id===id));};
  reorder(motor,['anforderung','vergleich','richtung','transistor','leistung','anschluesse','wasser','schaltplan','programm','motor-pwm','uebersetzung','test']);
  reorder(project,['planung','arbeitsplan','meilensteine','teamsitzung','pakete','integration','abnahme','abgabe','abschluss']);
  project.steps.find(s=>s.id==='pakete').title='Arbeitspakete mit Prüfkriterien ergänzen';

  const replaceMaterial=(file,description,type='Arbeitsblatt · PDF')=>{const m=MATERIALS.find(x=>x.file===file);if(m){m.description=description;m.type=type;}};
  replaceMaterial('Servomotor_Original.pdf','Schülerfassung mit korrigierter Servoversorgung, Pinvergleich und Winkelprogramm.');
  replaceMaterial('Schreibtischlampe.pdf','Schülerfassung für die Drei-Stufen-Lampe: Taster mit INPUT_PULLUP, PWM und eindeutige Zustandsfolge.');
  replaceMaterial('Statik.pdf','Aktualisierte Schülerfassung V4: Belastungen, Messreihen, Knicken, Aussteifung und Balkenformel. Ohne Erwartungshorizont.');
  MATERIALS.push(
    {title:'DC-Motor und Leistungstransistor',file:'Motor_Leistungstransistor.pdf',type:'Arbeitsblatt · PDF',description:'Überarbeitete Schülerfassung mit korrekter Stromangabe, vollständigem Motorzweig und Heftaufträgen.'},
    {title:'Getriebe und Lagerung',file:'Getriebe.pdf',type:'Arbeitsblatt · PDF',description:'Getriebearten, radiale und axiale Lagerung, Übersetzung, Fahrrad und Drehrichtungen.'},
    {title:'Arbeitsplan',file:'Arbeitsplan.pdf',type:'Planungsvorlage · PDF',description:'Arbeitspakete, Verantwortung und tatsächlicher Abschluss. Für das Projekt in Klasse 9 angepasst.'},
    {title:'Meilensteine',file:'Meilensteine.pdf',type:'Planungsvorlage · PDF',description:'Überprüfbare Zwischenziele mit Soll- und Ist-Terminen. Ohne vorgegebene alte Abgabetermine.'},
    {title:'Seifenblasenlösung',file:'Seifenblasenloesung.pdf',type:'Versuchsmaterial · PDF',description:'Die zwei Startrezepte, kleine Proben, vier Becher und ein nachvollziehbares Versuchsprotokoll.'},
    {title:'Reflexionsbogen',file:'Reflexionsbogen.pdf',type:'Reflexion · PDF',description:'Alle acht Bereiche: technische Lösung, Zusammenarbeit, Planung und persönlicher Beitrag.'},
    {title:'Arduino-Wiederholung mit Lampenhilfen',file:'Folien_Arduino_Wiederholung.pdf',type:'Unterrichtsfolien · PDF',description:'Erweiterte Wiederholung, schrittweise Lampenhilfen, PWM und Servo. Fachlich präzisierte Schülerfassung.'},
    {title:'Servomotor und Antriebe',file:'Folien_Servomotor.pdf',type:'Unterrichtsfolien · PDF',description:'Servo-Anwendungen und Übergang zum DC-Motor. Schülerfassung mit Anschluss-Hinweisen.'},
    {title:'DC-Motor und Getriebe',file:'Folien_Motor_Getriebe.pdf',type:'Unterrichtsfolien · PDF',description:'Motorleistung, Transistor und Getriebe. Schülerfassung ohne direkte Motoranschlüsse an Signalpins.'},
    {title:'Statik: Versuche und Biegung',file:'Folien_Statik.pdf',type:'Unterrichtsfolien · PDF',description:'Belastungen, Fadenversuche, Stützen, Knicken, Rahmen und Profile.'},
    {title:'Projektauftrag und Dokumentation',file:'Folien_Projekt.pdf',type:'Unterrichtsfolien · PDF',description:'Aktueller Materialrahmen, Arbeitsplanung und Abgabeunterlagen. Ohne namentliche Gruppenliste und alte Termine.'}
  );
})();
